### ISSUE TITLE
I do not really understand this sentence

### ISSUE THREAD

**Issue by tronta** [Relm4/book#30]
May be somebody can help me understanding this sentence better:
https://github.com/Relm4/book/blob/9a9dced99f8ff7ce9251b4ecb55aa1ebfbe24171/src/basic_concepts/basics/components.md?plain=1#L11

If there is already an implementation for every type, why do I need to implement one?

**Comment by AaronErhardt** [comment]
The sentence is basically a summary of [blanket implementations](https://stackoverflow.com/questions/73861891/what-are-blanket-implementations-in-rust). If your type implements SimpleComponent, a generic Component implementation will also implement Component for this type. Internationally, only Component is used, which works for both trait thanks to the blanket implementation. This is similar to From which has a blanket implementation for Into.
Also, implementing both manually will throw an error.

Maybe you have an idea to make this easier to understand?

**Comment by tronta** [comment]
Thanks for sharing. Again something new learned.

My try:
> As `SimpleCompoment` is automatically converted into a `Component` you can decide which one you want to implement.

**Comment by AaronErhardt** [comment]
It's not actually converted though. It's more like inheritance in other languages: SimpleComponent would be a sub-class of Component in C++ for example. SimpleComponent is still its own trait, but it automatically implements Component for you, so you can treat it as if your type was a regular Component.

**Comment by tronta** [comment]
take two:
When using `SimpleComponent` a default implementations for the missing functions are automatically created, so you can pick either one of the two.

**Comment by AaronErhardt** [comment]
Also not 100% correct. `SimpleComponent` not just implements the missing methods, it is it's own standalone trait. 
Also, default implementations are actually used in [another context](https://doc.rust-lang.org/book/ch10-02-traits.html#default-implementations) so this will only lead to more confusion, I assume.

Maybe we can put it like this: For every implementation of `SimpleComponent` Relm4 will also implement `Component` automatically. You just need to implement one of them and your type will implement `Component` either way. This is called blanket implementation and is used for traits like From in the standard library too [insert useful link here].

**Comment by tronta** [comment]
For me that would be a big improvement.

**Comment by AaronErhardt** [comment]
Awesome, it's always good to address some unclear sentences in the book. Do you want to send a PR?

**Comment by tronta** [comment]
Sure I'll do. Thanks.

**Comment by tronta** [comment]
Would this be a useful link? https://doc.rust-lang.org/book/ch10-02-traits.html

**Comment by AaronErhardt** [comment]
I think this would be more precise: https://doc.rust-lang.org/book/ch10-02-traits.html#using-trait-bounds-to-conditionally-implement-methods

**Comment by tronta** [comment]
https://github.com/Relm4/book/pull/31
