### ISSUE TITLE
"Your first app" explains 0.4 code instead of 0.5

### ISSUE THREAD

**Issue by ArekPiekarz** [Relm4/book#39]
The explanation of "Your first app" at https://relm4.org/book/stable/first_app.html still describes how to use Relm4 at version 0.4 instead of 0.5. It also links to a full example code on github, but it is written for 0.5 - https://github.com/Relm4/Relm4/blob/main/examples/simple_manual.rs

**Comment by AaronErhardt** [comment]
Thanks for reporting, let me know if you notice something else :)
